[package]
name = "jono"
description = "Priority Job Queue on Redis"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["produce"]
produce = ["dep:jono_produce"]

[dependencies]
jono_core = { path = "../jono_core" }
jono_produce = { path = "../jono_produce", default-features = false, optional = true }
